### ISSUE TITLE
The sentence mix is not very clear.

### ISSUE THREAD

**Issue by danieldumma** [pop123123123/CLI_sentence_mixing#15]
It works, but I'm not very convinced by the sentence mix; it's not very clear, perhaps because the MFA Aligner is outdated. The one in the library uses this version: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/tag/v1.1.0-beta.2. Maybe if the sentence-mixing is used with the latest version of the MFA Aligner, which is https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases, the sentence mix would be better understood.

**Comment by chippyman888** [comment]
> It works, but I'm not very convinced by the sentence mix; it's not very clear, perhaps because the MFA Aligner is outdated. The one in the library uses this version: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/tag/v1.1.0-beta.2. Maybe if the sentence-mixing is used with the latest version of the MFA Aligner, which is https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases, the sentence mix would be better understood.

mind telling me how you even got it to work in the first place considering that Youtube-dl is outdated?

**Comment by danieldumma** [comment]
Tutorial

Sentence Mixing CLI: https://github.com/pop123123123/CLI_sentence_mixing
Montreal Forced Aligner Updated: https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/releases/tag/v1.0.1
Move folder montreal-forced-aligner
Create folder SM-Dictionaries
Download model acoustic spanish: https://github.com/MontrealCorpusTools/mfa-models/releases/download/acoustic-archive-v1.0/spanish.zip
Move spanish.zip in pretrained_models
Dictionary Spanish: https://www.mediafire.com/file/d2igg1vc7g4gzcr/spanish.dict/file
Move spanish.dict in SM-Dictionaries in es
Consonant Vowel Spanish: https://github.com/nbusser/SM-Dictionaries/blob/master/es/es_consonant_vowel.dict
Move es_consonant_vowel.dict in SM-Dictionaries in es
Download config.json: https://www.mediafire.com/file/iw7o12d476geiqe/config.json/file
Move config.json in sentence mixing cli
Download vlc: https://www.videolan.org/vlc/index.es.html
Install vlc
Add vlc in system variables
Download ffmpeg: https://github.com/BtbN/FFmpeg-Builds/releases
Unzip and move ffmpeg.exe in sentence mixing cli
pip install sentence-mixing==2.0.2

Use: python video_creator_main.py -c "vlc --play-and-exit --no-repeat --no-loop {}" config.json link youtube

Every time you create a new sentence mix for a new video, you have to delete the MFA folder located in Documents, or else it will result in an error

Some videos do not work, as you will see in the tutorial

Tutorial video

https://www.youtube.com/watch?v=shizanhRywg

**Comment by MartinXimo** [comment]
i followed your tutorial and got this error "Traceback (most recent call last):
  File "F:\thing25\video_creator_main.py", line 80, in <module>
    main(
  File "F:\thing25\video_creator_main.py", line 22, in main
    total_timestamps, total_text, videos = loop_interface(
  File "F:\thing25\cli_interface.py", line 73, in loop_interface
    videos = list(video_futures)[0]
  File "F:\pythonthreepointnine\lib\concurrent\futures\_base.py", line 600, in result_iterator
    yield fs.pop().result()
  File "F:\pythonthreepointnine\lib\concurrent\futures\_base.py", line 433, in result
    return self.__get_result()
  File "F:\pythonthreepointnine\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "F:\pythonthreepointnine\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "F:\pythonthreepointnine\lib\site-packages\sentence_mixing\sentence_mixer.py", line 79, in get_videos
    videos = video_processing.preprocess_and_align(video_urls, rand)
  File "F:\pythonthreepointnine\lib\site-packages\sentence_mixing\logic\video_processing.py", line 226, in preprocess_and_align
    videos = _create_videos(video_urls)
  File "F:\pythonthreepointnine\lib\site-packages\sentence_mixing\logic\video_processing.py", line 21, in _create_videos
    paths = _dl_videos(video_urls)
  File "F:\pythonthreepointnine\lib\site-packages\sentence_mixing\logic\video_processing.py", line 69, in _dl_videos
    with yt_dlp.YoutubeDL(ydl_opts) as ydl:
  File "F:\pythonthreepointnine\lib\site-packages\yt_dlp\YoutubeDL.py", line 756, in __init__
    self.add_default_info_extractors()
  File "F:\pythonthreepointnine\lib\site-packages\yt_dlp\YoutubeDL.py", line 852, in add_default_info_extractors
    all_ies = {ie.IE_NAME.lower(): ie for ie in gen_extractor_classes()}
  File "F:\pythonthreepointnine\lib\site-packages\yt_dlp\extractor\__init__.py", line 11, in gen_extractor_classes
    from .extractors import _ALL_CLASSES
ImportError: cannot import name '_ALL_CLASSES' from partially initialized module 'yt_dlp.extractor.extractors' (most likely due to a circular import) (F:\pythonthreepointnine\lib\site-packages\yt_dlp\extractor\extractors.py)"

**Comment by MartinXimo** [comment]
nvm found out the error i put more than one yt link
