### ISSUE TITLE
The command "aligner" is either misspelled or could not be found.

### ISSUE THREAD

**Issue by CrazyPlaysHD** [pop123123123/CLI_sentence_mixing#5]
The command "aligner" is either misspelled or could not be found.

How can I fix this

**Comment by CrazyPlaysHD** [comment]
[https://cdn.discordapp.com/attachments/272814335238340608/836282653690036294/errornigger.PNG](url)

**Comment by CrazyPlaysHD** [comment]
https://cdn.discordapp.com/attachments/272814335238340608/836283003944173599/errornig.PNG

**Comment by nbusser** [comment]
Could you send us your config file and the location of MFA your filesystem ?

**Comment by CrazyPlaysHD** [comment]
config.json


**{
    "align_exe": "aligner/bin/mfa_align.exe",
    "trained_model": "aligner/pretrained_models/english.zip",
    "dict_path": "aligner/SM-Dictionaries/en/english.dict",
    "dict_consonant_vowel_path": "aligner/SM-Dictionaries/en/en_consonant_vowel.dict",
    "lang": "en",
    "folder": ".subs"
}**

**Comment by nbusser** [comment]
It looks like you are running the script in windows.  
Windows' paths are with backslashes, not slashes.  
Change your config file with this one:
```
{
"align_exe": "aligner\\bin\\mfa_align.exe",
"trained_model": "aligner\\pretrained_models\\english.zip",
"dict_path": "aligner\\SM-Dictionaries\\en\\english.dict",
"dict_consonant_vowel_path": "aligner\\SM-Dictionaries\\en\\en_consonant_vowel.dict",
"lang": "en",
"folder": ".subs"
}
```
Please give feedback

**Comment by CrazyPlaysHD** [comment]
> It looks like you are running the script in windows.
> Windows' paths are with backslashes, not slashes.
> Change your config file with this one:
> 
> ```
> {
> "align_exe": "aligner\\bin\\mfa_align.exe",
> "trained_model": "aligner\\pretrained_models\\english.zip",
> "dict_path": "aligner\\SM-Dictionaries\\en\\english.dict",
> "dict_consonant_vowel_path": "aligner\\SM-Dictionaries\\en\\en_consonant_vowel.dict",
> "lang": "en",
> "folder": ".subs"
> }
> ```
> 
> Please give feedback

Enter a sentence: city
downloading...
Traceback (most recent call last):
  File "video_creator_main.py", line 84, in <module>
  File "video_creator_main.py", line 23, in main
  File "cli_interface.py", line 74, in loop_interface
  File "sentence_mixing\sentence_mixer.py", line 87, in process_sm
  File "sentence_mixing\logic\analyze.py", line 132, in get_n_best_combos
  File "sentence_mixing\model\choice.py", line 184, in get_combos
  File "sentence_mixing\model\choice.py", line 144, in _create_children
  File "sentence_mixing\model\choice.py", line 265, in __init__
  File "sentence_mixing\model\choice.py", line 230, in compute_child_step_3_score
  File "sentence_mixing\logic\analyze_step_3.py", line 55, in step_3_audio_amplitude_rating
  File "sentence_mixing\logic\audio_analysis.py", line 43, in rate_amplitude_similarity
  File "sentence_mixing\logic\audio_analysis.py", line 43, in <listcomp>
  File "sentence_mixing\logic\audio_analysis.py", line 26, in get_normalized_rms
  File "sentence_mixing\model\audio.py", line 26, in get_wave
  File "sentence_mixing\model\audio.py", line 100, in _get_original_wave
  File "sentence_mixing\model\audio.py", line 80, in _get_original_wave
  File "sentence_mixing\model\audio.py", line 53, in _get_original_wave
  File "sentence_mixing\model\video.py", line 33, in get_audio_wave
  File "scipy\io\wavfile.py", line 639, in read
FileNotFoundError: [Errno 2] No such file or directory: '.downloads\\pzhuajGmKvM.All lego city ads.wav'
[2072] Failed to execute script video_creator_main
Der Befehl "t" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
